/**
 * Which animation clips each baked enemy model actually HAS.
 *
 * This is a fact about the pipeline's output, not a rendering decision: the
 * client's logical mapping (idle → `Flying_Idle` for a floater) stays in the
 * client, but "does `enemies_mushnub` own a clip called Punch" is one answer
 * both repos need — the panel to refuse an ability that would animate nothing,
 * the game to know what it can play.
 *
 * It matters because the Quaternius bundle rigs its models in three families
 * with NON-interchangeable names: walkers attack with `Bite_Front`, floaters
 * with `Headbutt`/`Punch`, humanoids with `Punch`/`Weapon`, and the walkers
 * even spell the hit react differently (`HitRecieve`). Naming a clip the rig
 * does not have is silent: the swing still lands, it just plays nothing. That
 * shipped once — the P5 Spore Lobber's panic swat asked a mushnub for `Punch`.
 *
 * GENERATED — do not edit. Run `pnpm assets:clips` after baking enemy models.
 * It reads the animation list out of each `assets_baked/enemies/*.glb`, which
 * is the only source that cannot be wrong about what a rig owns.
 */
export const ENEMY_MODEL_CLIPS: Record<string, readonly string[]> = {
  enemies_alpaking: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_alpaking_evolved: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_armabee: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_armabee_evolved: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_birb: ['Bite_Front', 'Dance', 'Death', 'HitRecieve', 'Idle', 'Jump', 'No', 'Walk', 'Yes'],
  enemies_blue_demon: [
    'Death',
    'Duck',
    'HitReact',
    'Idle',
    'Jump',
    'Jump_Idle',
    'Jump_Land',
    'No',
    'Punch',
    'Run',
    'Run2',
    'Walk',
    'Wave',
    'Weapon',
    'Yes',
  ],
  enemies_bunny: [
    'Death',
    'Duck',
    'HitReact',
    'Idle',
    'Jump',
    'Jump_Idle',
    'Jump_Land',
    'No',
    'Punch',
    'Run',
    'Walk',
    'Wave',
    'Weapon',
    'Yes',
  ],
  enemies_cactoro: [
    'Bite_Front',
    'Dance',
    'Death',
    'HitRecieve',
    'Idle',
    'Jump',
    'No',
    'Walk',
    'Yes',
  ],
  enemies_cat: ['Bite_Front', 'Dance', 'Death', 'HitRecieve', 'Idle', 'Jump', 'No', 'Walk', 'Yes'],
  enemies_chicken: [
    'Bite_Front',
    'Dance',
    'Death',
    'HitRecieve',
    'Idle',
    'Jump',
    'No',
    'Walk',
    'Yes',
  ],
  enemies_demon: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_dino: [
    'Death',
    'Duck',
    'HitReact',
    'Idle',
    'Jump',
    'Jump_Idle',
    'Jump_Land',
    'No',
    'Punch',
    'Run',
    'Walk',
    'Wave',
    'Weapon',
    'Yes',
  ],
  enemies_dragon: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_dragon_evolved: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_frog: [
    'Death',
    'Duck',
    'HitReact',
    'Idle',
    'Jump',
    'Jump_Idle',
    'Jump_Land',
    'No',
    'Punch',
    'Run',
    'Walk',
    'Wave',
    'Weapon',
    'Yes',
  ],
  enemies_ghost: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_ghost_skull: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_glub: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_glub_evolved: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_goleling: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_goleling_evolved: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_green_blob: [
    'Bite_Front',
    'Dance',
    'Death',
    'HitRecieve',
    'Idle',
    'Jump',
    'No',
    'Walk',
    'Yes',
  ],
  enemies_hywirl: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_monkroose: [
    'Death',
    'Duck',
    'HitReact',
    'Idle',
    'Jump',
    'Jump_Idle',
    'Jump_Land',
    'No',
    'Punch',
    'Run',
    'Walk',
    'Wave',
    'Weapon',
    'Yes',
  ],
  enemies_mushnub: [
    'Bite_Front',
    'Dance',
    'Death',
    'HitRecieve',
    'Idle',
    'Jump',
    'No',
    'Walk',
    'Yes',
  ],
  enemies_mushnub_evolved: [
    'Bite_Front',
    'Dance',
    'Death',
    'HitRecieve',
    'Idle',
    'Jump',
    'No',
    'Walk',
    'Yes',
  ],
  enemies_mushroom_king: [
    'Death',
    'Duck',
    'HitReact',
    'Idle',
    'Jump',
    'Jump_Idle',
    'Jump_Land',
    'No',
    'Punch',
    'Run',
    'Walk',
    'Wave',
    'Weapon',
    'Yes',
  ],
  enemies_ninja: [
    'Bite_Front',
    'Dance',
    'Death',
    'HitRecieve',
    'Idle',
    'Jump',
    'No',
    'Walk',
    'Yes',
  ],
  enemies_orc: [
    'Death',
    'Duck',
    'HitReact',
    'Idle',
    'Jump',
    'Jump_Idle',
    'Jump_Land',
    'No',
    'Punch',
    'Run',
    'Walk',
    'Wave',
    'Weapon',
    'Yes',
  ],
  enemies_orc_enemy: [
    'Bite_Front',
    'Dance',
    'Death',
    'HitRecieve',
    'Idle',
    'Jump',
    'No',
    'Walk',
    'Yes',
  ],
  enemies_pigeon: [
    'Bite_Front',
    'Dance',
    'Death',
    'HitRecieve',
    'Idle',
    'Jump',
    'No',
    'Walk',
    'Yes',
  ],
  enemies_pink_blob: [
    'Bite_Front',
    'Dance',
    'Death',
    'HitRecieve',
    'Idle',
    'Jump',
    'No',
    'Walk',
    'Yes',
  ],
  enemies_skeleton_mage: [
    'Death_A',
    'Hit_A',
    'Idle_A',
    'Idle_B',
    'Interact',
    'Running_A',
    'Throw',
    'Walking_A',
  ],
  enemies_skeleton_minion: [
    'Death_A',
    'Hit_A',
    'Idle_A',
    'Idle_B',
    'Interact',
    'Running_A',
    'Throw',
    'Walking_A',
  ],
  enemies_skeleton_rogue: [
    'Death_A',
    'Hit_A',
    'Idle_A',
    'Idle_B',
    'Interact',
    'Running_A',
    'Throw',
    'Walking_A',
  ],
  enemies_skeleton_warrior: [
    'Death_A',
    'Hit_A',
    'Idle_A',
    'Idle_B',
    'Interact',
    'Running_A',
    'Throw',
    'Walking_A',
  ],
  enemies_squidle: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_tribal: [
    'Death',
    'Fast_Flying',
    'Flying_Idle',
    'Headbutt',
    'HitReact',
    'No',
    'Punch',
    'Yes',
  ],
  enemies_wizard: [
    'Bite_Front',
    'Dance',
    'Death',
    'HitRecieve',
    'Idle',
    'Jump',
    'No',
    'Walk',
    'Yes',
  ],
  enemies_yeti: ['Bite_Front', 'Dance', 'Death', 'HitRecieve', 'Idle', 'Jump', 'No', 'Walk', 'Yes'],
};
