/**
 * Environment configuration — validated once at boot, fail-fast on anything missing
 * or malformed (docs/tech/ARCHITECTURE.md §6).
 */

import { z } from 'zod';

const schema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  HOST: z.string().default('127.0.0.1'),
  PORT: z.coerce.number().int().min(1).max(65535).default(8081),

  /** Peppers/secrets. Real values are generated by deploy/DEPLOY.sh on the VPS. */
  SESSION_PEPPER: z.string().min(8).default('dev-only-pepper-change-me'),
  OPS_SECRET: z.string().min(8).default('dev-only-ops-secret-change-me'),

  /** Where published map/content artifacts live (P12+). */
  PUBLISHED_DIR: z.string().default('./.published'),

  /** Dev client origin allowed to open a WebSocket. */
  CLIENT_ORIGIN: z.string().default('http://localhost:5173'),

  /** Hard cap on simultaneous players (docs/design/GAME_DESIGN.md §7: 5–20 expected). */
  MAX_PLAYERS: z.coerce.number().int().min(1).max(200).default(50),

  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace']).default('info'),
});

export type Config = z.infer<typeof schema>;

export const loadConfig = (env: NodeJS.ProcessEnv = process.env): Config => {
  const parsed = schema.safeParse(env);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((issue) => `  ${issue.path.join('.') || '(root)'}: ${issue.message}`)
      .join('\n');
    throw new Error(`Invalid server environment:\n${issues}`);
  }
  return parsed.data;
};
