/**
 * Environment configuration — validated once at boot, fail-fast on anything missing
 * or malformed (docs/tech/ARCHITECTURE.md §6).
 */

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

const DEV_DATABASE_URL = 'postgres://dawned:dawned@127.0.0.1:5432/dawned';
const DEV_OPS_SECRET = 'dev-only-ops-secret-change-me';

/** Repo-relative default for baked map artifacts (works from src/ and dist/). */
const DEFAULT_MAP_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../..',
  'assets_baked/map',
);

const schema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  HOST: z.string().default('127.0.0.1'),
  PORT: z.coerce.number().int().min(1).max(65535).default(8081),

  /** Postgres connection. Defaults to the local dev instance; explicit in prod. */
  DATABASE_URL: z.url().default(DEV_DATABASE_URL),

  /** Optional invite code — empty/absent = open registration (Q8 decision). */
  INVITE_CODE: z.string().max(64).optional(),

  /** Peppers/secrets. Real values are generated by deploy/DEPLOY.sh on the VPS. */
  SESSION_PEPPER: z.string().min(8).default('dev-only-pepper-change-me'),
  OPS_SECRET: z.string().min(8).default(DEV_OPS_SECRET),
  // (the default is refused when NODE_ENV=production — see the check below)

  /** Where published map/content artifacts live (P12+). */
  PUBLISHED_DIR: z.string().default('./.published'),

  /** Baked map artifacts root; the active version (shared MAP_VERSION) lives under it. */
  MAP_DIR: z.string().default(DEFAULT_MAP_DIR),

  /** Dev client origin allowed to open a WebSocket. */
  CLIENT_ORIGIN: z.string().default('http://localhost:5173'),

  /** Hard cap on simultaneous players (docs/design/GAME_DESIGN.md §7: 5–20 expected). */
  MAX_PLAYERS: z.coerce.number().int().min(1).max(200).default(50),

  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace']).default('info'),
});

export type Config = z.infer<typeof schema>;

export const loadConfig = (env: NodeJS.ProcessEnv = process.env): Config => {
  const parsed = schema.safeParse(env);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((issue) => `  ${issue.path.join('.') || '(root)'}: ${issue.message}`)
      .join('\n');
    throw new Error(`Invalid server environment:\n${issues}`);
  }
  const config = parsed.data;
  // Production must configure its own database — silently using the dev default
  // there would "work" against a wrong/empty DB, which is worse than failing.
  if (config.NODE_ENV === 'production' && config.DATABASE_URL === DEV_DATABASE_URL) {
    throw new Error(
      'DATABASE_URL must be set explicitly in production (see /etc/dawned/game.env).',
    );
  }
  // Same argument for the ops secret, and a sharper one: the default is a
  // literal in a public repository, and `/ops/*` grants items, sets levels and
  // teleports players. DEPLOY.sh generates a real one, so this only fires on a
  // box someone provisioned by hand — which is exactly the box that would never
  // notice.
  if (config.NODE_ENV === 'production' && config.OPS_SECRET === DEV_OPS_SECRET) {
    throw new Error(
      'OPS_SECRET must be set explicitly in production — the default is public. ' +
        'Generate one with: openssl rand -hex 32   (then set it in /etc/dawned/game.env ' +
        "and in the panel's admin.env, which must match).",
    );
  }
  return config;
};
