-- P4 combat seeds: the first published enemy/spawner content (NPCS_ENEMIES.md
-- bestiary Dawnshore rows + training dummies). Authored here because the A1
-- editors arrive alongside P5 — from then on content flows drafts → publish.
-- Positions are walkgrid-validated on map dev-2 (see P4-B in ROADMAP.md).
-- Idempotent: re-running a deploy migration must never duplicate content.
INSERT INTO "content_enemies" ("id", "status", "def") VALUES ('enemy_training_dummy', 'published', '{"id":"enemy_training_dummy","name":"Training Dummy","archetype":"dummy","rank":"normal","levelMin":1,"levelMax":1,"modelRef":"enemies_mushnub","scale":1.25,"hitRadius":0.55,"hitHeight":1.5,"moveSpeed":0.5,"statOverrides":{"maxHp":300,"armor":0},"abilities":[],"aggroRadius":2,"leashRadius":10,"socialTag":null,"xpMult":0}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_enemies" ("id", "status", "def") VALUES ('enemy_shore_glub', 'published', '{"id":"enemy_shore_glub","name":"Shore Glub","archetype":"swarm","rank":"normal","levelMin":1,"levelMax":2,"modelRef":"enemies_glub","scale":1,"hitRadius":0.45,"hitHeight":1,"moveSpeed":3.2,"statOverrides":{},"abilities":[{"id":"glub_headbutt","weight":3,"cooldownMs":1500,"rangeMin":0,"rangeMax":1.8,"kind":"melee_arc","coef":1,"reach":1.6,"angleDeg":70,"projectileSpeed":18,"projectileRadius":0.3,"circleRadius":2.5,"windupMs":600,"recoverMs":700,"telegraph":false,"clip":"Headbutt"},{"id":"glub_tackle","weight":1,"cooldownMs":6000,"rangeMin":0,"rangeMax":2.2,"kind":"melee_arc","coef":1.3,"reach":1.8,"angleDeg":80,"projectileSpeed":18,"projectileRadius":0.3,"circleRadius":2.5,"windupMs":900,"recoverMs":900,"telegraph":true,"clip":"Punch"}],"aggroRadius":8,"leashRadius":40,"socialTag":"shore_glubs","xpMult":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_enemies" ("id", "status", "def") VALUES ('enemy_young_mushnub', 'published', '{"id":"enemy_young_mushnub","name":"Young Mushnub","archetype":"grunt","rank":"normal","levelMin":3,"levelMax":5,"modelRef":"enemies_mushnub","scale":1,"hitRadius":0.5,"hitHeight":1.3,"moveSpeed":3.6,"statOverrides":{},"abilities":[{"id":"mushnub_bite","weight":3,"cooldownMs":1200,"rangeMin":0,"rangeMax":2.1,"kind":"melee_arc","coef":1,"reach":1.9,"angleDeg":80,"projectileSpeed":18,"projectileRadius":0.3,"circleRadius":2.5,"windupMs":550,"recoverMs":650,"telegraph":false,"clip":"Bite_Front"},{"id":"mushnub_lunge","weight":1,"cooldownMs":8000,"rangeMin":0,"rangeMax":2.8,"kind":"melee_arc","coef":1.6,"reach":2.4,"angleDeg":60,"projectileSpeed":18,"projectileRadius":0.3,"circleRadius":2.5,"windupMs":1100,"recoverMs":1000,"telegraph":true,"clip":"Jump"}],"aggroRadius":10,"leashRadius":40,"socialTag":"mushnubs","xpMult":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_spawners" ("id", "status", "def") VALUES ('spawner_dummy_west', 'published', '{"id":"spawner_dummy_west","kind":"point","x":-6,"z":382,"radius":0,"entries":[{"enemyId":"enemy_training_dummy","count":1,"level":1}],"respawnMs":15000,"campTag":null,"nightOnly":false}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_spawners" ("id", "status", "def") VALUES ('spawner_dummy_mid', 'published', '{"id":"spawner_dummy_mid","kind":"point","x":0,"z":381,"radius":0,"entries":[{"enemyId":"enemy_training_dummy","count":1,"level":1}],"respawnMs":15000,"campTag":null,"nightOnly":false}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_spawners" ("id", "status", "def") VALUES ('spawner_dummy_east', 'published', '{"id":"spawner_dummy_east","kind":"point","x":6,"z":382,"radius":0,"entries":[{"enemyId":"enemy_training_dummy","count":1,"level":1}],"respawnMs":15000,"campTag":null,"nightOnly":false}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_spawners" ("id", "status", "def") VALUES ('spawner_shore_glub_camp', 'published', '{"id":"spawner_shore_glub_camp","kind":"area","x":0,"z":330,"radius":7,"entries":[{"enemyId":"enemy_shore_glub","count":5,"level":null}],"respawnMs":120000,"campTag":"shore_glub_camp","nightOnly":false}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_spawners" ("id", "status", "def") VALUES ('spawner_shore_glub_west', 'published', '{"id":"spawner_shore_glub_west","kind":"area","x":-14,"z":312,"radius":5,"entries":[{"enemyId":"enemy_shore_glub","count":2,"level":null}],"respawnMs":90000,"campTag":"shore_glub_west","nightOnly":false}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_spawners" ("id", "status", "def") VALUES ('spawner_mushnub_meadow', 'published', '{"id":"spawner_mushnub_meadow","kind":"area","x":0,"z":270,"radius":5,"entries":[{"enemyId":"enemy_young_mushnub","count":2,"level":null}],"respawnMs":100000,"campTag":"mushnub_meadow","nightOnly":false}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_spawners" ("id", "status", "def") VALUES ('spawner_mushnub_path', 'published', '{"id":"spawner_mushnub_path","kind":"area","x":-12,"z":242,"radius":5,"entries":[{"enemyId":"enemy_young_mushnub","count":2,"level":null}],"respawnMs":100000,"campTag":"mushnub_path","nightOnly":false}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
