-- P10 content seeds: the gathering catalogue — 42 material/gem/proc/fish
-- items and 21 resource-node definitions (5 tiers × 4 professions, plus
-- Dawnpetal), authored THROUGH the Dawned-Admin Professions editor (A1-e) and
-- published via its rail; these rows are that output, frozen for deploys.
-- ON CONFLICT DO NOTHING: a panel-retuned live row must never be reverted by a
-- redeploy. (Doctrine: seed files are append-only history — repairs ship as NEW
-- migrations, never edits.)
--
-- Two rows here are REPAIRS to P8 content rather than new rows, and a fresh
-- database gets them from 0012 first, so the ON CONFLICT keeps the old value
-- and the UPDATE below fixes it: `item_material_dawnpetal` was authored at
-- ilvl 4 before the professions ladder existed and is the Elder Grove's T5
-- rare per PROFESSIONS.md §4, and `loot_dawnshore_spore` dropped it off a
-- level-3 mob. Meadowbell — the herb that shore actually grows — takes its
-- slot in the table.
--
-- PLACEMENTS are deliberately NOT here. Where a birch stands lives in the map
-- bake (`placements.json`), which deploy/BACKUP.sh archives and a map publish
-- rewrites; duplicating it into SQL would give the world two sources of truth
-- about the same forest. Re-plant with Dawned-Admin's tools/content/author-nodes.mjs.
-- content_items: 42 published rows
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_acacia_log', 'published', '{"id":"item_material_acacia_log","icon":"lorc/tree-branch","ilvl":21,"name":"Sungraze Acacia","slot":"none","bound":false,"stack":50,"stats":{},"value":11,"effect":null,"flavor":"Grew wide instead of tall. There was nothing to compete with.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_ashback_carp', 'published', '{"id":"item_material_ashback_carp","icon":"delapouite/whale-tail","ilvl":15,"name":"Ashback Carp","slot":"none","bound":false,"stack":20,"stats":{},"value":13,"effect":null,"flavor":"Grey on top and worth it underneath.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_ashwood_log', 'published', '{"id":"item_material_ashwood_log","icon":"lorc/dead-wood","ilvl":27,"name":"Ashwood Log","slot":"none","bound":false,"stack":50,"stats":{},"value":13,"effect":null,"flavor":"Petrified long enough ago that nobody remembers the fire.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_birchwood_log', 'published', '{"id":"item_material_birchwood_log","icon":"delapouite/wood-beam","ilvl":3,"name":"Birchwood Log","slot":"none","bound":false,"stack":50,"stats":{},"value":3,"effect":null,"flavor":"Pale, light, and forgiving of a first swing.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_cinder_eel', 'published', '{"id":"item_material_cinder_eel","icon":"delapouite/eel","ilvl":15,"name":"Cinder Eel","slot":"none","bound":false,"stack":20,"stats":{},"value":33,"effect":null,"flavor":"Warm all the way along, which is not how eels work.","rarity":"rare","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_cinderleaf', 'published', '{"id":"item_material_cinderleaf","icon":"lorc/leaf-skeleton","ilvl":15,"name":"Cinderleaf","slot":"none","bound":false,"stack":50,"stats":{},"value":8,"effect":null,"flavor":"Curls tighter the warmer it gets, like it is bracing.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_crag_fang', 'published', '{"id":"item_material_crag_fang","icon":"delapouite/shark-fin","ilvl":27,"name":"Crag Fang","slot":"none","bound":false,"stack":20,"stats":{},"value":20,"effect":null,"flavor":"The canyon pools are cold, deep, and occupied.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_dawn_sprat', 'published', '{"id":"item_material_dawn_sprat","icon":"delapouite/circling-fish","ilvl":3,"name":"Dawn Sprat","slot":"none","bound":false,"stack":20,"stats":{},"value":4,"effect":null,"flavor":"Travels in numbers because it has nothing else going for it.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_dawnpetal', 'published', '{"id":"item_material_dawnpetal","icon":"delapouite/herbs-bundle","ilvl":27,"name":"Dawnpetal","slot":"none","bound":false,"stack":50,"stats":{},"value":34,"effect":null,"flavor":"Opens at first light and closes on anyone who is late.","rarity":"rare","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_dawnstone', 'published', '{"id":"item_material_dawnstone","icon":"lorc/crystal-growth","ilvl":27,"name":"Dawnstone","slot":"none","bound":false,"stack":50,"stats":{},"value":21,"effect":null,"flavor":"Holds a little light of its own, and does not say where it got it.","rarity":"uncommon","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_deepsea_drum', 'published', '{"id":"item_material_deepsea_drum","icon":"delapouite/sperm-whale","ilvl":27,"name":"Deepsea Drum","slot":"none","bound":false,"stack":20,"stats":{},"value":20,"effect":null,"flavor":"You hear it before the line moves. Everyone says that. It is true.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_duneswimmer', 'published', '{"id":"item_material_duneswimmer","icon":"delapouite/manta-ray","ilvl":21,"name":"Duneswimmer","slot":"none","bound":false,"stack":20,"stats":{},"value":43,"effect":null,"flavor":"Glides where the water is thinnest, as if the sand were the point.","rarity":"rare","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_duskthorn', 'published', '{"id":"item_material_duskthorn","icon":"lorc/thorny-vine","ilvl":27,"name":"Duskthorn","slot":"none","bound":false,"stack":50,"stats":{},"value":13,"effect":null,"flavor":"Draws blood on the way into the bag and again on the way out.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_emberbark_log', 'published', '{"id":"item_material_emberbark_log","icon":"lorc/burning-tree","ilvl":15,"name":"Emberbark Log","slot":"none","bound":false,"stack":50,"stats":{},"value":8,"effect":null,"flavor":"Warm to the touch an hour after felling.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_emberkoi', 'published', '{"id":"item_material_emberkoi","icon":"delapouite/fish-monster","ilvl":15,"name":"Emberkoi","slot":"none","bound":false,"stack":20,"stats":{},"value":13,"effect":null,"flavor":"Orange in the water, red on the line, black in the pan.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_gem_amethyst', 'published', '{"id":"item_material_gem_amethyst","icon":"delapouite/rupee","ilvl":3,"name":"Rough Amethyst","slot":"none","bound":false,"stack":20,"stats":{},"value":14,"effect":null,"flavor":"Purple all the way through, which is rarer than the colour.","rarity":"uncommon","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_gem_diamond', 'published', '{"id":"item_material_gem_diamond","icon":"lorc/diamond-hard","ilvl":27,"name":"Rough Diamond","slot":"none","bound":false,"stack":20,"stats":{},"value":106,"effect":null,"flavor":"Survived whatever made the canyon. It will survive you.","rarity":"rare","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_gem_emerald', 'published', '{"id":"item_material_gem_emerald","icon":"lorc/gem-chain","ilvl":15,"name":"Rough Emerald","slot":"none","bound":false,"stack":20,"stats":{},"value":66,"effect":null,"flavor":"The Weald grows one of these about as often as it grows an oak.","rarity":"rare","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_gem_obsidian', 'published', '{"id":"item_material_gem_obsidian","icon":"lorc/stone-block","ilvl":21,"name":"Obsidian Shard","slot":"none","bound":false,"stack":20,"stats":{},"value":53,"effect":null,"flavor":"An edge that was never sharpened and never needed to be.","rarity":"uncommon","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_gem_sapphire', 'published', '{"id":"item_material_gem_sapphire","icon":"lorc/saphir","ilvl":9,"name":"Rough Sapphire","slot":"none","bound":false,"stack":20,"stats":{},"value":28,"effect":null,"flavor":"Cold in the palm long after you stop holding it up to the light.","rarity":"uncommon","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_gem_sunstone', 'published', '{"id":"item_material_gem_sunstone","icon":"lorc/sun-radiations","ilvl":27,"name":"Sunstone","slot":"none","bound":false,"stack":20,"stats":{},"value":106,"effect":null,"flavor":"Warm at dawn, warmer at noon, and warm all night.","rarity":"rare","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_geode', 'published', '{"id":"item_material_geode","icon":"lorc/rock","ilvl":9,"name":"Sealed Geode","slot":"none","bound":false,"stack":20,"stats":{},"value":26,"effect":null,"flavor":"Heavy, hollow, and refusing to say which.","rarity":"uncommon","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_ghostfin', 'published', '{"id":"item_material_ghostfin","icon":"lorc/ghost","ilvl":9,"name":"Ghostfin","slot":"none","bound":false,"stack":20,"stats":{},"value":23,"effect":null,"flavor":"Only ever caught after dark, and never twice in one night.","rarity":"rare","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_gold_ore', 'published', '{"id":"item_material_gold_ore","icon":"delapouite/gold-stack","ilvl":21,"name":"Gold Ore","slot":"none","bound":false,"stack":50,"stats":{},"value":11,"effect":null,"flavor":"The ravine gives it up easily. That should worry you.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_golden_sap', 'published', '{"id":"item_material_golden_sap","icon":"delapouite/honey-jar","ilvl":21,"name":"Golden Sap","slot":"none","bound":false,"stack":50,"stats":{},"value":38,"effect":null,"flavor":"Runs slowly enough that you can watch a full jar fill.","rarity":"uncommon","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_goldjaw_bass', 'published', '{"id":"item_material_goldjaw_bass","icon":"delapouite/dolphin","ilvl":21,"name":"Goldjaw Bass","slot":"none","bound":false,"stack":20,"stats":{},"value":17,"effect":null,"flavor":"Eats anything that fits and tries the rest anyway.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_heartwood', 'published', '{"id":"item_material_heartwood","icon":"delapouite/tree-growth","ilvl":15,"name":"Heartwood","slot":"none","bound":false,"stack":20,"stats":{},"value":84,"effect":null,"flavor":"One tree in a hundred has a core worth the axe. This was one.","rarity":"rare","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_iron_ore', 'published', '{"id":"item_material_iron_ore","icon":"lorc/metal-bar","ilvl":9,"name":"Iron Ore","slot":"none","bound":false,"stack":50,"stats":{},"value":6,"effect":null,"flavor":"Heavier than it looks, which is the first thing every apprentice learns.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_meadowbell', 'published', '{"id":"item_material_meadowbell","icon":"lorc/daisy","ilvl":3,"name":"Meadowbell","slot":"none","bound":false,"stack":50,"stats":{},"value":3,"effect":null,"flavor":"Rings in wind nobody else can feel.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_mossbloom', 'published', '{"id":"item_material_mossbloom","icon":"delapouite/grass","ilvl":9,"name":"Mossbloom","slot":"none","bound":false,"stack":50,"stats":{},"value":6,"effect":null,"flavor":"Glows faintly for about an hour after picking. Nobody knows why.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_mossgill_perch', 'published', '{"id":"item_material_mossgill_perch","icon":"delapouite/fish-scales","ilvl":9,"name":"Mossgill Perch","slot":"none","bound":false,"stack":20,"stats":{},"value":9,"effect":null,"flavor":"Green enough to lose in the shallows it lives in.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_resin', 'published', '{"id":"item_material_resin","icon":"lorc/dripping-honey","ilvl":3,"name":"Tree Resin","slot":"none","bound":false,"stack":50,"stats":{},"value":3,"effect":null,"flavor":"Sticks to the bag, the hand, and eventually the memory.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_rough_stone', 'published', '{"id":"item_material_rough_stone","icon":"delapouite/stone-pile","ilvl":3,"name":"Rough Stone","slot":"none","bound":false,"stack":50,"stats":{},"value":2,"effect":null,"flavor":"Every vein gives some. Every vendor takes some.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_seeds', 'published', '{"id":"item_material_seeds","icon":"delapouite/seedling","ilvl":9,"name":"Wild Seeds","slot":"none","bound":false,"stack":50,"stats":{},"value":8,"effect":null,"flavor":"Whatever these grow into, it is not growing in a backpack.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_silverline_ore', 'published', '{"id":"item_material_silverline_ore","icon":"lorc/metal-scales","ilvl":15,"name":"Silverline Ore","slot":"none","bound":false,"stack":50,"stats":{},"value":8,"effect":null,"flavor":"Runs through the ruin stone like a vein through a wrist.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_steppe_pike', 'published', '{"id":"item_material_steppe_pike","icon":"lorc/sea-dragon","ilvl":21,"name":"Steppe Pike","slot":"none","bound":false,"stack":20,"stats":{},"value":17,"effect":null,"flavor":"Long, patient, and out of patience the moment it sees the lure.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_sunblossom', 'published', '{"id":"item_material_sunblossom","icon":"delapouite/sunflower","ilvl":21,"name":"Sunblossom","slot":"none","bound":false,"stack":50,"stats":{},"value":11,"effect":null,"flavor":"Tall enough to see over the grass, which is the whole strategy.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_sunscale', 'published', '{"id":"item_material_sunscale","icon":"delapouite/clownfish","ilvl":3,"name":"Sunscale","slot":"none","bound":false,"stack":20,"stats":{},"value":11,"effect":null,"flavor":"Comes up gold and stays gold for about four seconds.","rarity":"rare","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_the_old_one', 'published', '{"id":"item_material_the_old_one","icon":"lorc/tentacle-strike","ilvl":27,"name":"The Old One","slot":"none","bound":false,"stack":20,"stats":{},"value":555,"effect":null,"flavor":"It let go. That is the part nobody mentions afterwards.","rarity":"epic","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_tidenibbler', 'published', '{"id":"item_material_tidenibbler","icon":"delapouite/piranha","ilvl":3,"name":"Tidenibbler","slot":"none","bound":false,"stack":20,"stats":{},"value":4,"effect":null,"flavor":"Takes the bait, the hook, and a little of the finger.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_weald_trout', 'published', '{"id":"item_material_weald_trout","icon":"lorc/fishbone","ilvl":9,"name":"Weald Trout","slot":"none","bound":false,"stack":20,"stats":{},"value":9,"effect":null,"flavor":"Fights the whole way in and sulks afterwards.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_items" ("id", "status", "def") VALUES ('item_material_wealdoak_log', 'published', '{"id":"item_material_wealdoak_log","icon":"delapouite/log","ilvl":9,"name":"Wealdoak Log","slot":"none","bound":false,"stack":50,"stats":{},"value":6,"effect":null,"flavor":"Older than the path that leads to it.","rarity":"common","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;

-- content_resource_nodes: 21 published rows
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_fishing_deepsea', 'published', '{"id":"node_fishing_deepsea","name":"Deepsea Sandbar","tier":5,"procs":[],"radius":2,"yields":[{"itemId":"item_material_crag_fang","qtyMax":2,"qtyMin":1,"weight":6},{"itemId":"item_material_deepsea_drum","qtyMax":1,"qtyMin":1,"weight":4},{"itemId":"item_material_the_old_one","qtyMax":1,"qtyMin":1,"weight":1}],"modelRef":"world_nature_swordfish","channelMs":3000,"respawnMs":180000,"bonusRolls":0,"profession":"fishing","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_fishing_dune_water', 'published', '{"id":"node_fishing_dune_water","name":"Steppe Water","tier":4,"procs":[],"radius":1.6,"yields":[{"itemId":"item_material_goldjaw_bass","qtyMax":2,"qtyMin":1,"weight":5},{"itemId":"item_material_steppe_pike","qtyMax":1,"qtyMin":1,"weight":4},{"itemId":"item_material_duneswimmer","qtyMax":1,"qtyMin":1,"weight":1}],"modelRef":"world_nature_yellow_tang","channelMs":3000,"respawnMs":150000,"bonusRolls":0,"profession":"fishing","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_fishing_ember_run', 'published', '{"id":"node_fishing_ember_run","name":"Ember Run","tier":3,"procs":[],"radius":1.6,"yields":[{"itemId":"item_material_emberkoi","qtyMax":2,"qtyMin":1,"weight":5},{"itemId":"item_material_ashback_carp","qtyMax":1,"qtyMin":1,"weight":4},{"itemId":"item_material_cinder_eel","qtyMax":1,"qtyMin":1,"weight":1}],"modelRef":"world_nature_red_snapper","channelMs":3000,"respawnMs":120000,"bonusRolls":0,"profession":"fishing","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_fishing_shore_shoal', 'published', '{"id":"node_fishing_shore_shoal","name":"Shore Shoal","tier":1,"procs":[],"radius":1.6,"yields":[{"itemId":"item_material_dawn_sprat","qtyMax":2,"qtyMin":1,"weight":5},{"itemId":"item_material_tidenibbler","qtyMax":1,"qtyMin":1,"weight":4},{"itemId":"item_material_sunscale","qtyMax":1,"qtyMin":1,"weight":1}],"modelRef":"world_nature_goldfish","channelMs":3000,"respawnMs":90000,"bonusRolls":0,"profession":"fishing","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_fishing_weald_pool', 'published', '{"id":"node_fishing_weald_pool","name":"Weald Pool","tier":2,"procs":[],"radius":1.6,"yields":[{"itemId":"item_material_mossgill_perch","qtyMax":2,"qtyMin":1,"weight":5},{"itemId":"item_material_weald_trout","qtyMax":1,"qtyMin":1,"weight":3},{"itemId":"item_material_silver_trout","qtyMax":1,"qtyMin":1,"weight":2},{"itemId":"item_material_ghostfin","qtyMax":1,"qtyMin":1,"weight":1}],"modelRef":"world_nature_koi","channelMs":3000,"respawnMs":105000,"bonusRolls":0,"profession":"fishing","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_herbalism_cinderleaf', 'published', '{"id":"node_herbalism_cinderleaf","name":"Cinderleaf","tier":3,"procs":[{"itemId":"item_material_seeds","qtyMax":2,"qtyMin":1,"weight":1}],"radius":1,"yields":[{"itemId":"item_material_cinderleaf","qtyMax":2,"qtyMin":1,"weight":1}],"modelRef":"world_nature_fern_1","channelMs":3000,"respawnMs":120000,"bonusRolls":0,"profession":"herbalism","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_herbalism_dawnpetal', 'published', '{"id":"node_herbalism_dawnpetal","name":"Dawnpetal","tier":5,"procs":[{"itemId":"item_material_seeds","qtyMax":2,"qtyMin":1,"weight":1}],"radius":1.1,"yields":[{"itemId":"item_material_dawnpetal","qtyMax":1,"qtyMin":1,"weight":1}],"modelRef":"world_nature_flower_5_clump","channelMs":3000,"respawnMs":600000,"bonusRolls":1,"profession":"herbalism","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_herbalism_duskthorn', 'published', '{"id":"node_herbalism_duskthorn","name":"Duskthorn","tier":5,"procs":[{"itemId":"item_material_seeds","qtyMax":2,"qtyMin":1,"weight":1}],"radius":1.1,"yields":[{"itemId":"item_material_duskthorn","qtyMax":2,"qtyMin":1,"weight":1}],"modelRef":"world_nature_bush_small_flowers","channelMs":3000,"respawnMs":180000,"bonusRolls":0,"profession":"herbalism","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_herbalism_meadowbell', 'published', '{"id":"node_herbalism_meadowbell","name":"Meadowbell","tier":1,"procs":[{"itemId":"item_material_seeds","qtyMax":2,"qtyMin":1,"weight":1}],"radius":0.9,"yields":[{"itemId":"item_material_meadowbell","qtyMax":2,"qtyMin":1,"weight":1}],"modelRef":"world_nature_flower_1_clump","channelMs":3000,"respawnMs":90000,"bonusRolls":0,"profession":"herbalism","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_herbalism_mossbloom', 'published', '{"id":"node_herbalism_mossbloom","name":"Mossbloom","tier":2,"procs":[{"itemId":"item_material_seeds","qtyMax":2,"qtyMin":1,"weight":1}],"radius":0.9,"yields":[{"itemId":"item_material_mossbloom","qtyMax":2,"qtyMin":1,"weight":1}],"modelRef":"world_nature_flower_2_clump","channelMs":3000,"respawnMs":105000,"bonusRolls":0,"profession":"herbalism","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_herbalism_sunblossom', 'published', '{"id":"node_herbalism_sunblossom","name":"Sunblossom","tier":4,"procs":[{"itemId":"item_material_seeds","qtyMax":2,"qtyMin":1,"weight":1}],"radius":1,"yields":[{"itemId":"item_material_sunblossom","qtyMax":2,"qtyMin":1,"weight":1}],"modelRef":"world_nature_flower_4_clump","channelMs":3000,"respawnMs":150000,"bonusRolls":0,"profession":"herbalism","depletedModelRef":null}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_mining_copper', 'published', '{"id":"node_mining_copper","name":"Copper Vein","tier":1,"procs":[{"itemId":"item_material_geode","qtyMax":1,"qtyMin":1,"weight":2},{"itemId":"item_material_gem_amethyst","qtyMax":1,"qtyMin":1,"weight":1}],"radius":1.2,"yields":[{"itemId":"item_material_copper_ore","qtyMax":2,"qtyMin":1,"weight":3},{"itemId":"item_material_rough_stone","qtyMax":3,"qtyMin":1,"weight":2}],"modelRef":"world_nature_rock_2_a_color1","channelMs":3000,"respawnMs":90000,"bonusRolls":0,"profession":"mining","depletedModelRef":"world_nature_rock_1_c_color1"}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_mining_dawnstone', 'published', '{"id":"node_mining_dawnstone","name":"Dawnstone Vein","tier":5,"procs":[{"itemId":"item_material_gem_diamond","qtyMax":1,"qtyMin":1,"weight":1},{"itemId":"item_material_gem_sunstone","qtyMax":1,"qtyMin":1,"weight":1}],"radius":1.2,"yields":[{"itemId":"item_material_dawnstone","qtyMax":2,"qtyMin":1,"weight":3},{"itemId":"item_material_rough_stone","qtyMax":3,"qtyMin":1,"weight":2}],"modelRef":"world_nature_rock_3_h_color1","channelMs":3000,"respawnMs":180000,"bonusRolls":0,"profession":"mining","depletedModelRef":"world_nature_rock_1_c_color1"}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_mining_gold', 'published', '{"id":"node_mining_gold","name":"Gold Vein","tier":4,"procs":[{"itemId":"item_material_geode","qtyMax":1,"qtyMin":1,"weight":2},{"itemId":"item_material_gem_obsidian","qtyMax":1,"qtyMin":1,"weight":1}],"radius":1.2,"yields":[{"itemId":"item_material_gold_ore","qtyMax":2,"qtyMin":1,"weight":3},{"itemId":"item_material_rough_stone","qtyMax":3,"qtyMin":1,"weight":2}],"modelRef":"world_nature_rock_2_e_color1","channelMs":3000,"respawnMs":150000,"bonusRolls":0,"profession":"mining","depletedModelRef":"world_nature_rock_1_c_color1"}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_mining_iron', 'published', '{"id":"node_mining_iron","name":"Iron Vein","tier":2,"procs":[{"itemId":"item_material_geode","qtyMax":1,"qtyMin":1,"weight":2},{"itemId":"item_material_gem_sapphire","qtyMax":1,"qtyMin":1,"weight":1}],"radius":1.2,"yields":[{"itemId":"item_material_iron_ore","qtyMax":2,"qtyMin":1,"weight":3},{"itemId":"item_material_rough_stone","qtyMax":3,"qtyMin":1,"weight":2}],"modelRef":"world_nature_rock_2_c_color1","channelMs":3000,"respawnMs":105000,"bonusRolls":0,"profession":"mining","depletedModelRef":"world_nature_rock_1_c_color1"}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_mining_silverline', 'published', '{"id":"node_mining_silverline","name":"Silverline Vein","tier":3,"procs":[{"itemId":"item_material_geode","qtyMax":1,"qtyMin":1,"weight":2},{"itemId":"item_material_gem_emerald","qtyMax":1,"qtyMin":1,"weight":1}],"radius":1.2,"yields":[{"itemId":"item_material_silverline_ore","qtyMax":2,"qtyMin":1,"weight":3},{"itemId":"item_material_rough_stone","qtyMax":3,"qtyMin":1,"weight":2}],"modelRef":"world_nature_rock_3_d_color1","channelMs":3000,"respawnMs":120000,"bonusRolls":0,"profession":"mining","depletedModelRef":"world_nature_rock_1_c_color1"}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_woodcutting_acacia', 'published', '{"id":"node_woodcutting_acacia","name":"Sungraze Acacia","tier":4,"procs":[{"itemId":"item_material_golden_sap","qtyMax":1,"qtyMin":1,"weight":3},{"itemId":"item_material_heartwood","qtyMax":1,"qtyMin":1,"weight":1}],"radius":2,"yields":[{"itemId":"item_material_acacia_log","qtyMax":3,"qtyMin":1,"weight":1}],"modelRef":"world_nature_twistedtree_2","channelMs":3000,"respawnMs":150000,"bonusRolls":0,"profession":"woodcutting","depletedModelRef":"world_nature_wood_log_b"}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_woodcutting_ashwood', 'published', '{"id":"node_woodcutting_ashwood","name":"Ashwood","tier":5,"procs":[{"itemId":"item_material_golden_sap","qtyMax":1,"qtyMin":1,"weight":2},{"itemId":"item_material_heartwood","qtyMax":1,"qtyMin":1,"weight":1}],"radius":2,"yields":[{"itemId":"item_material_ashwood_log","qtyMax":3,"qtyMin":1,"weight":1}],"modelRef":"world_nature_deadtree_4","channelMs":3000,"respawnMs":180000,"bonusRolls":0,"profession":"woodcutting","depletedModelRef":"world_nature_wood_log_b"}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_woodcutting_birch', 'published', '{"id":"node_woodcutting_birch","name":"Birch","tier":1,"procs":[{"itemId":"item_material_resin","qtyMax":2,"qtyMin":1,"weight":1}],"radius":1.4,"yields":[{"itemId":"item_material_birchwood_log","qtyMax":3,"qtyMin":1,"weight":1}],"modelRef":"world_nature_birchtree_2","channelMs":3000,"respawnMs":90000,"bonusRolls":0,"profession":"woodcutting","depletedModelRef":"world_nature_wood_log_b"}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_woodcutting_emberbark', 'published', '{"id":"node_woodcutting_emberbark","name":"Emberbark","tier":3,"procs":[{"itemId":"item_material_resin","qtyMax":2,"qtyMin":1,"weight":3},{"itemId":"item_material_heartwood","qtyMax":1,"qtyMin":1,"weight":1}],"radius":1.8,"yields":[{"itemId":"item_material_emberbark_log","qtyMax":3,"qtyMin":1,"weight":1}],"modelRef":"world_nature_mapletree_2","channelMs":3000,"respawnMs":120000,"bonusRolls":0,"profession":"woodcutting","depletedModelRef":"world_nature_wood_log_b"}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_resource_nodes" ("id", "status", "def") VALUES ('node_woodcutting_wealdoak', 'published', '{"id":"node_woodcutting_wealdoak","name":"Wealdoak","tier":2,"procs":[{"itemId":"item_material_resin","qtyMax":2,"qtyMin":1,"weight":3},{"itemId":"item_material_heartwood","qtyMax":1,"qtyMin":1,"weight":1}],"radius":1.8,"yields":[{"itemId":"item_material_wealdoak_log","qtyMax":3,"qtyMin":1,"weight":1}],"modelRef":"world_nature_commontree_3","channelMs":3000,"respawnMs":105000,"bonusRolls":0,"profession":"woodcutting","depletedModelRef":"world_nature_wood_log_b"}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;

-- P8 repairs (see the header): applied with UPDATE because 0012 seeds these
-- ids first and the INSERTs above would be swallowed by ON CONFLICT.
UPDATE "content_items" SET "def" = '{"id":"item_material_dawnpetal","icon":"delapouite/herbs-bundle","ilvl":27,"name":"Dawnpetal","slot":"none","bound":false,"stack":50,"stats":{},"value":34,"effect":null,"flavor":"Opens at first light and closes on anyone who is late.","rarity":"rare","weapon":null,"category":"material","modelRef":null,"classLock":[],"armorClass":null,"consumable":null,"requiresLevel":1}'::jsonb WHERE "id" = 'item_material_dawnpetal' AND "status" = 'published' AND ("def"->>'ilvl')::int < 20;
UPDATE "content_loot_tables" SET "def" = '{"id":"loot_dawnshore_spore","name":"Dawnshore Spore-dwellers","entries":[{"kind":"nothing","weight":42},{"ref":"item_junk_spore_sac","kind":"item","maxQty":2,"minQty":1,"weight":16},{"ref":"item_junk_chipped_tusk","kind":"item","maxQty":1,"minQty":1,"weight":8},{"ref":"item_material_meadowbell","kind":"item","maxQty":1,"minQty":1,"weight":8},{"ref":"item_consumable_tonic_minor","kind":"item","maxQty":1,"minQty":1,"weight":6},{"ref":"item_consumable_antidote","kind":"item","maxQty":1,"minQty":1,"weight":4},{"kind":"gold","maxQty":9,"minQty":3,"weight":8},{"ref":"loot_dawnshore_gear","kind":"table","weight":12},{"ref":"loot_weald_gear","kind":"table","weight":4,"minKillerLevel":7}]}'::jsonb WHERE "id" = 'loot_dawnshore_spore' AND "status" = 'published' AND "def"::text LIKE '%item_material_dawnpetal%';
