-- P11 content seeds: the pilot quest set — 4 Dawnhaven/Weald NPCs and 8
-- quests (four Dawnshore one-offs that teach the verbs, plus the four-part
-- "The Loggers' Silence" chain), authored THROUGH the Dawned-Admin quest editor
-- (A4) and published via its rail; these rows are that output, frozen for
-- deploys.
-- ON CONFLICT DO NOTHING: a panel-retuned live row must never be reverted by a
-- redeploy. (Doctrine: seed files are append-only history — repairs ship as NEW
-- migrations, never edits.)
--
-- PLACEMENTS are deliberately NOT here, for the same reason P10's node seeds
-- left theirs out: where Marla STANDS, where the notice board is nailed up and
-- where a POI's discovery ring sits all live in the map bake
-- (`placements.json`), which deploy/BACKUP.sh archives and a map publish
-- rewrites. Duplicating them into SQL would give the world two sources of truth
-- about the same village. Re-place with Dawned-Admin's
-- tools/content/author-quests.mjs.

-- content_npcs: 4 published rows
INSERT INTO "content_npcs" ("id", "status", "def") VALUES ('npc_bran', 'published', '{"id":"npc_bran","name":"Bran","role":"villager","barks":[{"text":"…quiet. Please.","emote":""}],"scale":1,"title":"logger","idleClip":"Idle","talkClip":"","vendorId":null,"appearance":{"body":"m","hair":"parted","skin":0,"beard":false,"outfit":"peasant","hairColor":2,"outfitTint":1},"barkCooldownSec":90}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_npcs" ("id", "status", "def") VALUES ('npc_hesta', 'published', '{"id":"npc_hesta","name":"Hesta","role":"quest_giver","barks":[{"text":"The cut has been quiet three days now.","emote":""},{"text":"Whatever is in there, it is not a bear.","emote":""}],"scale":1,"title":"warden of the Weald","idleClip":"Idle","talkClip":"","vendorId":null,"appearance":{"body":"f","hair":"long","skin":2,"beard":false,"outfit":"ranger","hairColor":0,"outfitTint":1},"barkCooldownSec":40}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_npcs" ("id", "status", "def") VALUES ('npc_marla', 'published', '{"id":"npc_marla","name":"Marla","role":"quest_giver","barks":[{"text":"The bog took two fence posts this week.","emote":""},{"text":"Don''t drink from the pools out there.","emote":""}],"scale":1,"title":"Dawnhaven gate farmer","idleClip":"Idle","talkClip":"","vendorId":null,"appearance":{"body":"f","hair":"buns","skin":1,"beard":false,"outfit":"peasant","hairColor":2,"outfitTint":0},"barkCooldownSec":45}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_npcs" ("id", "status", "def") VALUES ('npc_torv', 'published', '{"id":"npc_torv","name":"Torv","role":"quest_giver","barks":[{"text":"Tide comes in fast on the flats. Mind yourself.","emote":""},{"text":"Every board on that jetty I laid myself.","emote":""}],"scale":1,"title":"harbourmaster","idleClip":"Idle","talkClip":"","vendorId":null,"appearance":{"body":"m","hair":"buzzed","skin":3,"beard":true,"outfit":"ranger","hairColor":2,"outfitTint":0},"barkCooldownSec":50}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;

-- content_quests: 8 published rows
INSERT INTO "content_quests" ("id", "status", "def") VALUES ('quest_shore_boil_trouble', 'published', '{"id":"quest_shore_boil_trouble","name":"Boil Trouble","giver":{"kind":"npc","npcId":"npc_marla"},"steps":[{"hint":{"x":-70,"z":210,"radius":80},"type":"kill","count":8,"hooks":[],"enemyId":"enemy_bog_blob","enemyTag":null,"trackerText":"Bog Blobs slain"}],"zoneId":"dawnshore","chainId":"","rewards":{"xp":220,"gold":35,"items":[{"qty":3,"itemId":"item_consumable_rations_travelers"}],"title":"","choices":[]},"dialogue":{"offer":[{"id":"offer","text":"My fence posts are dissolving. I would like the bog to stop doing that.","emote":"","npcId":"npc_marla","choices":[{"goto":"","text":"I''ll see to it.","action":"accept"},{"goto":"lore","text":"What is out there?","action":"goto"},{"goto":"","text":"Not just now.","action":"decline"}]},{"id":"lore","text":"Blobs. Wet ones. They were not this bold last spring.","emote":"","npcId":"npc_marla","choices":[{"goto":"","text":"I''ll see to it.","action":"accept"},{"goto":"","text":"Not just now.","action":"decline"}]}],"complete":[{"id":"done","text":"The fence is still standing. Take these, you have earned them.","emote":"","npcId":"npc_marla","choices":[{"goto":"","text":"Thank you.","action":"turn_in"}]}],"inProgress":[{"id":"wait","text":"Another post went yesterday.","emote":"","npcId":"npc_marla","choices":[{"goto":"","text":"Working on it.","action":"close"}]}]},"trackable":true,"repeatable":false,"journalText":"Marla''s fence posts are dissolving. She''d like the bog to stop doing that.","turnInNpcId":"npc_marla","prerequisites":{"level":2,"questIds":[],"discoveryIds":[]},"suggestedLevel":3}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_quests" ("id", "status", "def") VALUES ('quest_shore_driftwood', 'published', '{"id":"quest_shore_driftwood","name":"Driftwood for the Jetty","giver":{"kind":"board","boardId":"board_dawnhaven"},"steps":[{"hint":null,"type":"collect","count":6,"hooks":[],"itemId":"item_material_birchwood_log","source":"gather","trackerText":"Birchwood cut"},{"hint":null,"type":"deliver","count":6,"hooks":[],"npcId":"npc_torv","itemId":"item_material_birchwood_log","trackerText":"Deliver the wood to Torv"}],"zoneId":"dawnshore","chainId":"","rewards":{"xp":140,"gold":26,"items":[],"title":"","choices":[]},"dialogue":{"offer":[],"complete":[{"id":"done","text":"Good straight lengths. The jetty thanks you.","emote":"","npcId":"npc_torv","choices":[{"goto":"","text":"Take them.","action":"turn_in"}]}],"inProgress":[]},"trackable":true,"repeatable":false,"journalText":"A notice on the Dawnhaven board: six good lengths of birch wanted, jetty repairs, see Torv.","turnInNpcId":"npc_torv","prerequisites":{"level":1,"questIds":[],"discoveryIds":[]},"suggestedLevel":2}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_quests" ("id", "status", "def") VALUES ('quest_shore_glub_tide', 'published', '{"id":"quest_shore_glub_tide","name":"Glubs on the Tideline","giver":{"kind":"npc","npcId":"npc_torv"},"steps":[{"hint":{"x":40,"z":250,"radius":70},"type":"kill","count":5,"hooks":[],"enemyId":"enemy_shore_glub","enemyTag":null,"trackerText":"Shore Glubs cleared"}],"zoneId":"dawnshore","chainId":"","rewards":{"xp":90,"gold":14,"items":[],"title":"","choices":[]},"dialogue":{"offer":[{"id":"offer","text":"Glubs are up on the tideline again, chewing my mooring ropes. Thin them out and I will square you.","emote":"","npcId":"npc_torv","choices":[{"goto":"","text":"I can do that.","action":"accept"},{"goto":"","text":"Not just now.","action":"decline"}]}],"complete":[{"id":"done","text":"Ropes intact. That is a good morning.","emote":"","npcId":"npc_torv","choices":[{"goto":"","text":"Glad to help.","action":"turn_in"}]}],"inProgress":[{"id":"wait","text":"Still a few out there by the sound of it.","emote":"","npcId":"npc_torv","choices":[{"goto":"","text":"On it.","action":"close"}]}]},"trackable":true,"repeatable":false,"journalText":"Torv says the glubs have been at his mooring ropes. He would like fewer glubs.","turnInNpcId":"npc_torv","prerequisites":{"level":1,"questIds":[],"discoveryIds":[]},"suggestedLevel":1}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_quests" ("id", "status", "def") VALUES ('quest_shore_lost_crate', 'published', '{"id":"quest_shore_lost_crate","name":"The Lost Crate","giver":{"kind":"npc","npcId":"npc_torv"},"steps":[{"x":62,"z":232,"hint":null,"type":"explore","hooks":[],"radius":18,"clueText":"Past the last mooring post, where the gulls will not settle.","trackerText":"Find where the crate washed up"},{"hint":null,"type":"interact","count":1,"hooks":[{"hook":"toast","text":"Torv will want to know what was in this."}],"objectId":"chest_shore_lostnet","objectTag":null,"trackerText":"Open the crate"}],"zoneId":"dawnshore","chainId":"","rewards":{"xp":160,"gold":30,"items":[],"title":"","choices":[]},"dialogue":{"offer":[{"id":"offer","text":"A crate went over in the swell three nights back. If it beached, it beached east.","emote":"","npcId":"npc_torv","choices":[{"goto":"","text":"I''ll look for it.","action":"accept"},{"goto":"","text":"Not just now.","action":"decline"}]}],"complete":[{"id":"done","text":"Salt-ruined, but mine. Here — for the walk.","emote":"","npcId":"npc_torv","choices":[{"goto":"","text":"It was no trouble.","action":"turn_in"}]}],"inProgress":[{"id":"wait","text":"East. Past the last post.","emote":"","npcId":"npc_torv","choices":[{"goto":"","text":"Right.","action":"close"}]}]},"trackable":true,"repeatable":false,"journalText":"Torv lost a crate to the swell. He is fairly sure the sea gave it back somewhere east.","turnInNpcId":"npc_torv","prerequisites":{"level":1,"questIds":[],"discoveryIds":[]},"suggestedLevel":2}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_quests" ("id", "status", "def") VALUES ('quest_weald_silence_1', 'published', '{"id":"quest_weald_silence_1","name":"The Loggers'' Silence","giver":{"kind":"npc","npcId":"npc_hesta"},"steps":[{"x":-104,"z":104,"hint":null,"type":"explore","hooks":[],"radius":26,"clueText":"North-west, where the road gives out and the saw-cuts start.","trackerText":"Find the logging site"}],"zoneId":"dawnshore","chainId":"chain_loggers_silence","rewards":{"xp":420,"gold":48,"items":[],"title":"","choices":[]},"dialogue":{"offer":[{"id":"offer","text":"The cut has been silent three days. No axes, no singing, and nobody walked back out.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"I will go and look.","action":"accept"},{"goto":"lore","text":"How many were up there?","action":"goto"},{"goto":"","text":"Not just now.","action":"decline"}]},{"id":"lore","text":"Six. Bran among them, and Bran could talk the bark off a tree.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"I will go and look.","action":"accept"},{"goto":"","text":"Not just now.","action":"decline"}]}],"complete":[{"id":"done","text":"Empty. And the tools still there. That is worse, not better.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"It is.","action":"turn_in"}]}],"inProgress":[{"id":"wait","text":"North-west. Follow the road until it stops being one.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"Going.","action":"close"}]}]},"trackable":true,"repeatable":false,"journalText":"Hesta says the loggers stopped singing three days ago. Nobody has walked back down the road.","turnInNpcId":"npc_hesta","prerequisites":{"level":6,"questIds":[],"discoveryIds":[]},"suggestedLevel":8}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_quests" ("id", "status", "def") VALUES ('quest_weald_silence_2', 'published', '{"id":"quest_weald_silence_2","name":"What Took Them","giver":{"kind":"npc","npcId":"npc_hesta"},"steps":[{"hint":{"x":-104,"z":104,"radius":40},"type":"interact","count":4,"hooks":[{"hook":"toast","text":"Something moves in the treeline."}],"objectId":null,"objectTag":"Marked Stump","trackerText":"Marked stumps inspected"},{"hint":{"x":-104,"z":104,"radius":40},"type":"kill","count":3,"hooks":[],"enemyId":"enemy_weald_stalker","enemyTag":null,"trackerText":"Stalkers driven off"}],"zoneId":"dawnshore","chainId":"chain_loggers_silence","rewards":{"xp":520,"gold":60,"items":[],"title":"","choices":[]},"dialogue":{"offer":[{"id":"offer","text":"Look at the cuts themselves. A tree remembers what interrupted it.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"I will read the stumps.","action":"accept"},{"goto":"","text":"Not just now.","action":"decline"}]}],"complete":[{"id":"done","text":"Stalkers. They do not take six grown loggers. Something drove them down.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"Something did.","action":"turn_in"}]}],"inProgress":[{"id":"wait","text":"Four of them were marked for felling. Start there.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"Right.","action":"close"}]}]},"trackable":true,"repeatable":false,"journalText":"Four stumps, cut clean and abandoned mid-swing. Whatever came, it came fast.","turnInNpcId":"npc_hesta","prerequisites":{"level":6,"questIds":["quest_weald_silence_1"],"discoveryIds":[]},"suggestedLevel":9}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_quests" ("id", "status", "def") VALUES ('quest_weald_silence_3', 'published', '{"id":"quest_weald_silence_3","name":"The Hollow Trunk","giver":{"kind":"npc","npcId":"npc_hesta"},"steps":[{"hint":null,"type":"collect","count":5,"hooks":[],"itemId":"item_material_mossbloom","source":"gather","trackerText":"Mossbloom gathered"},{"hint":{"x":-118,"z":92,"radius":30},"type":"deliver","count":5,"hooks":[{"hook":"toast","text":"Bran will live. He would rather you kept your voice down."}],"npcId":"npc_bran","itemId":"item_material_mossbloom","trackerText":"Take the mossbloom to Bran"}],"zoneId":"dawnshore","chainId":"chain_loggers_silence","rewards":{"xp":620,"gold":70,"items":[{"qty":3,"itemId":"item_consumable_potion_lesser"}],"title":"","choices":[]},"dialogue":{"offer":[{"id":"offer","text":"One of them is alive. Bran, in a hollow trunk, and in no state to walk. Mossbloom, five heads, and be quick.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"Where does mossbloom grow?","action":"accept"},{"goto":"","text":"Not just now.","action":"decline"}]}],"complete":[{"id":"done","text":"He talked, then. Thank the roots for that.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"He did.","action":"turn_in"}]}],"inProgress":[{"id":"wait","text":"Mossbloom. The Weald is full of it if you look down.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"Going.","action":"close"}]}]},"trackable":true,"repeatable":false,"journalText":"Bran is alive in a hollow trunk and cannot walk. Mossbloom grows all over the Weald, if you look down.","turnInNpcId":"npc_hesta","prerequisites":{"level":6,"questIds":["quest_weald_silence_2"],"discoveryIds":[]},"suggestedLevel":10}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
INSERT INTO "content_quests" ("id", "status", "def") VALUES ('quest_weald_silence_4', 'published', '{"id":"quest_weald_silence_4","name":"The Crown Beneath","giver":{"kind":"npc","npcId":"npc_hesta"},"steps":[{"hint":{"x":-150,"z":60,"radius":60},"type":"kill","count":1,"hooks":[{"hook":"toast","text":"The Weald is quiet again. Properly, this time."}],"enemyId":"enemy_mushroom_king","enemyTag":null,"trackerText":"The Mushroom King"}],"zoneId":"dawnshore","chainId":"chain_loggers_silence","rewards":{"xp":900,"gold":120,"items":[],"title":"Friend of the Weald","choices":[{"qty":1,"itemId":"item_weapon_axe_wealdcleaver","classId":"warrior"},{"qty":1,"itemId":"item_weapon_dagger_mosswhisper","classId":"rogue"},{"qty":1,"itemId":"item_weapon_staff_sunspire","classId":"mage"},{"qty":1,"itemId":"item_weapon_mace_wealdward","classId":"cleric"}]},"dialogue":{"offer":[{"id":"offer","text":"Bran says it wore a crown. Everything under those trees answers to it, and it is still down there.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"Then it should not be.","action":"accept"},{"goto":"","text":"Not just now.","action":"decline"}]}],"complete":[{"id":"done","text":"The Weald breathes again. Take your pick — the loggers would want you armed.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"Thank you.","action":"turn_in"}]}],"inProgress":[{"id":"wait","text":"South-west of the cut. You will know it.","emote":"","npcId":"npc_hesta","choices":[{"goto":"","text":"I will.","action":"close"}]}]},"trackable":true,"repeatable":false,"journalText":"Bran says the thing under the trees wore a crown, and everything in the Weald answered to it.","turnInNpcId":"npc_hesta","prerequisites":{"level":8,"questIds":["quest_weald_silence_3"],"discoveryIds":[]},"suggestedLevel":11}'::jsonb) ON CONFLICT ("id", "status") DO NOTHING;
